#### image_utils example notebook

This is a simple notebook to demonstrate how to use the lsst.eo_utils.base.image_utils functions to:
* Get the image data from a particular CCD in a way that works for both butler and non-butler data
* Get the amplifier indices from the CCD data object for either butler
* Extract the data from the CCD data object in readout order for either bulter or non-butler data

import stuff

In [36]:
import numpy as np
from lsst.eo_utils.base import image_utils
from lsst.eo_utils.base import butler_utils
from lsst.eo_utils.base import file_utils

In [38]:
butler = butler_utils.get_butler_by_repo('TS8')
run = '6106D'
data_b = butler_utils.get_files_butler(butler, run, testtypes=['DARK'], imagetype='BIAS', outkey="BIAS")
data_f = file_utils.get_files_for_run(run, testtypes=['dark_raft_acq'], imagetype='bias', outkey='BIAS')
dataid_b = data_b['RTM-004']['S00']['BIAS'][0]
dataid_f = data_f['RTM-004']['S00']['BIAS'][0]
check_filename = butler.get('raw_filename', dataid_b)

Here we use the image_utils to get CCD-level data objects for both types of data.
Note that the object types are different

In [40]:
ccd_b = image_utils.get_ccd_from_id(butler, dataid_b, [])
ccd_f = image_utils.get_ccd_from_id(None, dataid_f, [])

In [41]:
type(ccd_b), type(ccd_f)

(lsst.afw.image.exposure.exposure.ExposureF,
 lsst.eotest.sensor.MaskedCCD.MaskedCCD)

Here we get the list of amps in both cases, not the difference in numbering

In [42]:
amps_b = image_utils.get_amp_list(ccd_b)
amps_f = image_utils.get_amp_list(ccd_f)
amps_b, amps_f

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

Here we get the data from both version of the image, in readout order, 
for the imaging and overscan regions

In [43]:
data_b = image_utils.get_data_as_read(ccd_b, 0)
data_f = image_utils.get_data_as_read(ccd_f, 1)

In [ ]:
data_b.keys(), data_f.keys()

Here we just 

In [46]:
data_b['imaging'] - data_b['imaging']

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [49]:
data_b['serial_overscan'] - data_b['serial_overscan']

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [50]:
data_b['parallel_overscan'] - data_b['parallel_overscan']

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)